### ISSUE TITLE
Enable all messages to use both notification and data payloads

### ISSUE THREAD

**Issue by PSanetra** [bytefish/FcmJava#1]
Hi,

at the moment you cannot send TopicMessages with a notification payload.
Are there reasons not to allow all messages to be sent with both payloads?

The fcm documentation states it is possible to have both payloads at the same time: https://firebase.google.com/docs/cloud-messaging/concept-options#messages-with-both-notification-and-data-payloads

PSanetra

**Comment by bytefish** [comment]
No I think I just forgot it. :sweat_smile: I will add the Notification Payload.

**Comment by bytefish** [comment]
I think the separation between a NotificationMessage and a DataMessage doesn't make any sense. There should be a Message class, which holds both the Data Payload and Notification. I would also add a MessageBuilder and TopicMessageBuilder to make it easier to build the Messages. 

What do you think?

**Comment by PSanetra** [comment]
Yes I think there should be only one Message class, which can hold both payloads at the same time. 

A single MessageBuilder may be ok. I would create a Recipient interface with getTo(), getRegistrationIds() and getCondition(). Then you can implement Recipient classes for RegistrationId, RegistrationIds, NotificationKey, Topic and TopicList. The MessageBuilder needs only a setRecipient() method.

**Comment by bytefish** [comment]
I added another constructor for the NotificationPayload to the Messages. The ``combined`` package has been removed and the ``data`` messages now have an additional constructor. The NotificationPayload will only be serialized to JSON if it is not null.

**Comment by bytefish** [comment]
Notification Payloads have been added to the messages. I am closing this issue.
