### ISSUE TITLE
message_id in FcmMessageResponse

### ISSUE THREAD

**Issue by culebras** [bytefish/FcmJava#11]
When analyzing  `TopicMessageResponse`, the field `message_id` contains a value, but when analyzing `FcmMessageResponse `the field `message_id` is always `null`.

I am also comparing that value with the `D/MainActivity: Key: google.message_id Value: 0:1485439662711057%d0e84a90d0e84a90` value received in the android application and that value is different from the value in the `TopicMessageResponse message_id` .

I am not sure if that is the behavior or both values should be the same.

**Comment by culebras** [comment]
I also found that `D/MainActivity: Key: google.message_id Value`:  is the same as the message_id not from `FcmMessageResponse `object, but from any of the items inside it.

**Comment by bytefish** [comment]
I have increased the Logging informations with commit 72ff2c1. If the ``message_id`` is null, then there is either a problem with the deserialization or the message itself. 

The Topic Message Response Format is in Table 6: https://firebase.google.com/docs/cloud-messaging/http-server-ref.

**Comment by culebras** [comment]
I will try to take a look into it this weekend if I have some free time.

**Comment by culebras** [comment]
Hi,

I added `toString `methods to response classes, it can be useful to print it when debugging. I also changed `message_id` in `TopicMessageResponse `to `long`, according to table 6 you mentioned in previous comment.

Also I removed `message_id` from `FcmMessageResponse`, because according to format described in the link you mentioned (table 5), `message_id` it is not present in the `FcmMessageResponse `itself, but in each of its `FcmMessageResultItem`.

I have created new pull request, you can take a look into it and check if it is ok.

**Comment by bytefish** [comment]
Great work! 😎
