### ISSUE TITLE
Create FcmMessageOptionsBuilder#setTimeToLive(int) to be compatible with Java 1.7

### ISSUE THREAD

**Issue by heese** [bytefish/FcmJava#14]
I know that Java 1.7 is kinda deprecated. However, I would appreciate it if you could add ```setTimeToLive(int ttlInSeconds)``` to ```FcmMessageOptionsBuilder```.

**Comment by culebras** [comment]
Hi,

You can add new setter method in the builder.

Also, remember that maximum time to live accepted in FCM platform is 4 weeks, so it would be also interesting to add a validation to the time to live setters methods.

**Comment by culebras** [comment]
You can add to the builder something like this:

```
 private static final int MAX_TIME_TO_LIVE = 2419200; // 4 weeks, in seconds

 public FcmMessageOptionsBuilder setTimeToLive(Duration timeToLive) {
         return setTimeToLive ((int) timeToLive.getSeconds());
    }

    public FcmMessageOptionsBuilder setTimeToLive(int seconds) {
        if (seconds > MAX_TIME_TO_LIVE) {
            throw new IllegalArgumentException("timeToLive cannot be greater than 4 weeks (2419200 seconds)");
        }
        this.timeToLive = seconds;
        return this;
    }
```

**Comment by bytefish** [comment]
I think it is better to have a separate method for it. For your application I would either write simple method, that sets the value in the ``FcmMessageOptions`` or you could implement a custom ``FcmMessageOptionsBuilder`` with the desired method.
