### ISSUE TITLE
Fcm Error

### ISSUE THREAD

**Issue by lmoal** [bytefish/FcmJava#19]
Hello,

an ErrorCodeEnum value is missing : 'InvalidApnsCredential', is it possible to add it ? 
One more thing is that error 'Invalid JSON' is not specified 'HTTP_STATUS_CODE = 400'. You throw an FcmGeneralException in StatusResponseInterceptor. Do you think it would be relevant to throw an FcmInvalidJsonException ? After that we could cover all possible 'error' from fcm (https://firebase.google.com/docs/cloud-messaging/http-server-ref#table9).

Thank you for your work !

**Comment by bytefish** [comment]
The InvalidApnsCredential Enum Value was missing. I have added it and release a new version.

**Comment by klem231188** [comment]
Hi, I think you forgot to release it on maven ;)
There is no InvalidApnsCredential in fcmjava-core-1.0.jar

**Comment by bytefish** [comment]
Yes! Sorry for the delay. :innocent: I have released 1.1 to the Maven Repositories with the additional Enum and some small fixes for Topic Messages.
