### ISSUE TITLE
FcmClient.send methods returning MulticastMessageResponse throw UnrecognizedPropertyExceptions

### ISSUE THREAD

**Issue by PSanetra** [bytefish/FcmJava#2]
Hi,

the FcmClient.send methods, which take DataMulticastMessage and NotificationMulticastMessage Arguments throw the following Exception:

java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "canonical_ids" (class de.bytefish.fcmjava.responses.MulticastMessageResponse), not marked as ignorable (11 known properties: "multicast_id", "success", "numberOfCanonicalIds", "results", "canoncial_ids", "failure", "message_id", "numberOfFailure", "multicastId", "numberOfSuccess", "messageId"])

This is because of a typo in the "canonical_ids" JsonProperty Annotiation of the MulticastMessageResponse.

I will create a PR to fix this and also add the annotation JsonIgnoreProperties(ignoreUnknown = true) to all response types, so that the library won't break if Google adds new properties to the JSON response.

PSanetra

**Comment by PSanetra** [comment]
Regarding https://github.com/bytefish/FcmJava/commit/cb7fbe1b5b1185ffdd202467dfe77df489b2f472

I believe it is better to ignore all unknown properties. If Google adds some property to a FCM response the library will break in all using projects and all projects must release a new version to update this library, even if they won't use the new property.

At least make the ObjectMapper in JsonUtils configurable, so developers can set `objectMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);`
(But I think using JsonIgnoreProperties(ignoreUnknown = true) on the response classes is cleaner)

**Comment by bytefish** [comment]
Thanks for your valuable input. Regarding Client APIs I always thought it is better to fail hard instead of silently parse with probably missing data. But chances are good I missed some properties in the FCM API, which cause the deserialization it to crash. Give me some time to think about it. ☺

**Comment by bytefish** [comment]
I have added the IgnoreProperties attribute for now.
