### ISSUE TITLE
Notification sent to topics are visible in Android notification tray

### ISSUE THREAD

**Issue by karikalankumaresan** [bytefish/FcmJava#22]
```
FcmMessageOptions options = FcmMessageOptions.builder()
         .setTimeToLive(Duration.ofHours(1))
         .setContentAvailable(Boolean.TRUE)  //Setting true for silent notification
         .build();

NotificationPayload payload = NotificationPayload.builder()
         .setBadge("0") // disable badge in ios
         .build();
         
PushNotificationData data = new PushNotificationData("new-data", new Date());
Topic pushToTopic = new Topic(topicId);
TopicMessageResponse response = client.send(new TopicUnicastMessage(options, pushToTopic, data, payload));
```

The above code sends a silent notification to iOS (it does not display notifications in the tray). However, the same code makes the notifications visible in the tray for Android. Is there any other setting needs to be done to avoid the notification in the tray for Android and iOS both?

Thanks in advance

**Comment by bytefish** [comment]
If you only want to send data without a notification, then use a Topic message like I did here:

* https://github.com/bytefish/FcmJava/blob/master/FcmJava/fcmjava-client/src/test/java/de/bytefish/fcmjava/client/tests/integration/FcmClientIntegrationTest.java#L64

This won't display Notifications in iOS and Android.

**Comment by karikalankumaresan** [comment]
Thanks for the response. However, I understand that the code I have sent follows the same approach as your reference (except the payload param to switch off the badges in iOS)? I could not see any other difference, but I still get the notification in the Android tray.

**Comment by bytefish** [comment]
If you do not pass a Notification Payload, you won't see a notification. Only pass the data you want to push to the device and don't pass a Notification Payload. This way no notification will be displayed in iOS and Android.

**Comment by karikalankumaresan** [comment]
It works. Thanks.
