### ISSUE TITLE
FcmJava with PoolingHttpClientConnectionManager Usage

### ISSUE THREAD

**Issue by benstse** [bytefish/FcmJava#23]
Hi:

I'm wanting to confirm if FcmJava can be used with PoolingHttpClientConnectionManager in multithread environment for higher performance.

I have code roughly as follows that uses the new FcmJava DefaultHttpClient with a new HttpClientBuilder that uses an existing pooling connection manager on each request. It seems to be working but I'm not sure if FcmJava is really re-using the connection from the pools or closing it each time. Here is roughly the code:

        // Created once
        PoolingHttpClientConnectionManager cm = new PoolingHttpClientConnectionManager()
                                        .setMaxTotal(10)
                                        .setDefaultMaxPerRoute(5);

        // Done per thread request
        // Setting shared was important for keeping the connection manager from shutting down
        HttpClientBuilder clientBuilder = HttpClients.custom()
                                            .setConnectionManager(cm)
                                            .setConnectionManagerShared(true);
        FcmClient client = new FcmClient(fcmSettings, new DefaultHttpClient(fcmSettings, clientBuilder));

        client.send(....)

With house FcmJava is implemented, does this give me the expected higher throughput using the connection pool as compared to  creating a FcmClient as:

     FcmClient client = new FcmClient(fmcSettings);
     client.send(....)

In looking at some of the FcmClient code and class DefaultHttpClient.java and the methods of 'internalPost' were making the request to FCM but closing the connection. 

Thanks.

**Comment by bytefish** [comment]
Yes, when I rewrote the ``DefaultHttpClient`` I also thought about using a Connection Pool and not shutting down the connection for each request. But I didn't have the time to implement it in a way, that I am safe to release. And I didn't find a lot of resources for best practices with a ``CloseableHttpClient``. 

I don't know when I will have the time to verify or evaluate your questions. Please do not expect a fast reply.

**Comment by benstse** [comment]
Thanks for your response. I'll try to spend some time to see if it works currently as expected as in the above code, if not, then I'll fallback to the basic usage without connection pool. And await for any future updates or conclusions you may have. Thanks.

**Comment by bytefish** [comment]
I have added an initial version for reusing the CloseableHttpClient instead of creating one for each request. I am quite sure the CloseableHttpClient has some kind of Connection Pooling inside, so it should have a good throughput. 

Maybe you can try the current implementation in the ``master`` branch and let me know about the performance.

**Comment by benstse** [comment]
Hi:

I was doing some testing with the code from master and for my testing, it seems to work.  I was using the 'master' with those changes, with code example as I put in the original issue. I'm definitely seeing better performance (under the right PoolingHttpClientConnectionManager() settings relative to the work load being sent to it).

I saw your diff changes and they made sense than the version I was using before.

In my preliminary findings, if the number of threads attempting to send message through were 
equal or less than than max total and or max per route, of course got better performance compared to using "FcmClient(fmcSettings)" constructor.
                .setMaxTotal(10)
               .setDefaultMaxPerRoute(5);


If you were to eventually get more validation of these changes and any other checks to confirm these changes are good, it would be nice to get it in regular release officially and then we make use of it.

Thanks for the the quick changes to allow me to check and looking forward to these enhancements getting in an official release.

**Comment by bytefish** [comment]
I have released Version 2.1 to the Maven repository. The ``IFcmClient`` now implements an ``AutoClosable`` as well, so all implementations of the interface have to release their resources.

**Comment by benstse** [comment]
Thank you so much for making this in a new release. I appreciate the great support and will work on integrating it.
