### ISSUE TITLE
Ability to provide a configured Object Mapper to the DefaultHttpClient

### ISSUE THREAD

**Issue by jaymes-bearden** [bytefish/FcmJava#25]
As per title -- I would like the ability to provide a customized Object Mapper to the DefaultHttpClient without rewriting/extending/implementing a new IHttpClient.

**Comment by bytefish** [comment]
In the next release an abstraction over the Json Deserialization will be added, so other Serializers can be easily plugged in and configured. This will be done in Release 2.2.

**Comment by bytefish** [comment]
I have added a ``IJsonSerializer`` interface with the referenced commit, so you can inject your own implementations. Thanks for your Pull Request and valuable advice. It will be released with 2.2, when I have added all pending changes.

**Comment by bytefish** [comment]
Ability to modify the Serializer is available in Version 2.2.
