### ISSUE TITLE
Support for iOS 10+ mutable_content

### ISSUE THREAD

**Issue by fjjimenez01** [bytefish/FcmJava#29]
Does the library supports mutable_content flag for iOS 10+ notifications?

https://firebase.google.com/docs/cloud-messaging/http-server-ref#downstream-http-messages-json

**Comment by bytefish** [comment]
I will look into it.

**Comment by bytefish** [comment]
The referenced commit adds the mutable_content flag. I will release it with 2.2.

**Comment by bytefish** [comment]
Added in 2.2.

**Comment by fjjimenez01** [comment]
Thanks a lot
