### ISSUE TITLE
Incorrect CreateDeviceGroupMessageResponse property

### ISSUE THREAD

**Issue by swiatek25** [bytefish/FcmJava#31]
Hi, 

Unfortunately `@JsonProperty` in constructor does not specify exact response key name. It should be `notification_key`. Could you please fix that in core module?

Thanks for your mapping and work on FCM

**Comment by bytefish** [comment]
Thanks for reporting! 😎 I will fix it and release a new version.

**Comment by bytefish** [comment]
I fixed it, wrote a Unit Test and released the new version to the Maven Central Repository. Please reopen the ticket, if it doesn't fix the problem. The release will be available within the next hours, since Maven only syncs in hour intervals.

**Comment by swiatek25** [comment]
Thanks for quick fix. Works fine!

**Comment by bytefish** [comment]
Thanks for the Feedback.
