### ISSUE TITLE
log4j.properties

### ISSUE THREAD

**Issue by julienrenaut** [bytefish/FcmJava#34]
Hello,

I believe the log4j.properties file should be removed from the published artifacts.

People (still) using log4j 1.x can run into trouble if that log4j.properties is read on the classpath instead of whatever is the intended log4j.properties file.

Thanks!

**Comment by bytefish** [comment]
I have deleted the log4j properties. Please reopen, if this doesn't fix the issues.

**Comment by julienrenaut** [comment]
Thanks. This solved the issue.
