### ISSUE TITLE
Exponential backoff for posting data to cloud

### ISSUE THREAD

**Issue by rajusubramaniam** [bytefish/FcmJava#4]
FCM/GCM recommends exponential backoff for posting data to cloud. Is that in pipe or any deadlines for the same?

**Comment by bytefish** [comment]
I have implemented a Simple Retry Strategy for Network Errors. This implementation respects the Retry-After Header sent by FCM for Status Codes between 500 and 600, as suggested in the documentation.

I think you also mean to resend the data with Exponential Backoff if Push Messages to a specific client fail. This will be a little trickier to implement. I don't have any plans to integrate it right now, but it would be great if you could contribute it to the project. :)

**Comment by bytefish** [comment]
I have added a class ``RetryUtils``, which can be used to Retry on Network Errors. You could easily plug in a new Retry Strategy into the methods.
