### ISSUE TITLE
Unicode issue

### ISSUE THREAD

**Issue by ChristianSchab** [bytefish/FcmJava#6]
I have also an issue with german umlauts.

Example:
```
String rcpt = "fyw...uJJLzSUlxnQXImRTbpLuxt";
FcmMessageOptions options = FcmMessageOptions.builder().setTimeToLive(Duration.ofHours(1)).build();
NotificationPayload payload = new NotificationPayload("für außen", "möglich", null, null, null, null, null, "https://www.example.com/", null, null, null, null);
NotificationUnicastMessage notificationMessage = new NotificationUnicastMessage(options, rcpt, payload);
new FcmClient(PropertiesBasedSettings.createFromDefault()).send(notificationMessage);
```

leads to such a message:

![fcm_message](https://cloud.githubusercontent.com/assets/17610709/21273189/af973f74-c3c2-11e6-9ad0-71533146c10d.jpg)

Has anyone else this problem?

**Comment by bytefish** [comment]
I guess it happens here: 

* https://github.com/bytefish/FcmJava/blob/master/FcmJava/fcmjava-client/src/main/java/de/bytefish/fcmjava/client/http/HttpClient.java#L95

I will fix it and write a test for it.

**Comment by bytefish** [comment]
It was due to a missing Charset in the HttpClient. Please let me know if version 0.5 fixes the problem.

**Comment by bytefish** [comment]
Please let me know if the latest release fixes the issue. :+1:

**Comment by ChristianSchab** [comment]
I just tested it and now it works!
Thank you a lot!

**Comment by bytefish** [comment]
Great. Thanks for the feedback.
