### ISSUE TITLE
Sending topic messages without data payload, only with notification payload.

### ISSUE THREAD

**Issue by culebras** [bytefish/FcmJava#9]
Hello, I am just wandering if would it nice to also allow to send messages to topics without data payload, only with notification payload.

Now `TopicMulticastMessage `and `TopicUnicastMessage `include constructors without Notification payload, but always is required to pass Object data.

I am trying to use `TopicUnicastMessage(FcmMessageOptions options, Topic to, Object data, NotificationPayload notification) `passing notification but leaving Object data to null, but I am having some issues.

If I find anything else related to this I will post again here.

**Comment by bytefish** [comment]
I have added the functionality, a test and released Version 0.8 of the library. It should be available in some hours.
